name: CI Demos

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  BRANCH: develop

jobs:
  build:
    strategy:
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]#, windows-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    # Placeholder for Docker on our Amazon AWS Runner
    #container:
    #  image: ubuntu-latest
    #  options: --user 1000


    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    #- name: clone repo
    #  run: git clone https://github.com/dtcc-platform/${{ github.event.repository.name }} -b $BRANCH && pwd
    - name: pip install MacOS/Ubuntu
      run: ls -alt && export PATH="$pythonLocation:$PATH" && python --version && export "DEB_PYTHON_INSTALL_LAYOUT=deb_system" && pip install .
      if: matrix.os != 'windows-latest'
    - name: pip install Windows
      run: pip install .  
      if: matrix.os == 'windows-latest'
      # ${{ github.event.repository.name }}/
    #  shell: bash {0}
    #- name: cmake install
    #  run: cd ${{ github.event.repository.name }}/build/ && cmake .. && make all && sudo make install && cd ..
    - name: run tests on MacOS/Linux
      run: cd demos && ls -alt
      if: matrix.os != 'windows-latest'
    - name: run tests on MacOS/Linux
      run: cd demos && dir 
      if: matrix.os == 'windows-latest'
   
